# 39. Funciones asíncronas

En 2017 (*ES8*) se introducen las palabras clave `async` / `await`, que no son más que una forma de azúcar sintáctico (*sugar syntax*) para gestionar las promesas de una forma más sencilla. Con `async` / `await` evitamos el uso encadenado de `then` para trabajar de una forma más cómoda.

Para declarar una función asíncrona debemos hacer uso de la palabra reservada `async`. Todo lo demás sigue igual:

```javascript
async function myFavouriteColor() {
    return 'black';
}

myFavouriteColor().then((data) => console.log(data)); // "black"

const myFavouriteNumber = async() => 14;

myFavouriteNumber().then((data) => console.log(data)); // 14
```

&nbsp;

Sin embargo utilizar únicamente `async` carece de sentido. Para eso contamos con la inestimable ayuda de `await`. Esta palabra reservada solo puede ser utilizada dentro de una función asíncrona. ¿Su finalidad? Esperar a que una promesa se resuelva antes de avanzar a la siguiente línea de código.

```javascript
// Creamos una nueva promesa que devuelve el valor "black" a los 3 segundos.
const myFavouriteColor = new Promise((resolve) => {
    setTimeout(() => {
        resolve('black');
    }, 3000);
});

// Creamos un arrow function asíncrona.
const getColor = async () => {
    // Intentamos acceder al valor de la promesa inmediatamente de forma
    // síncrona. Esto no funcionará porque no hemos esperado los 3 segundos.
    console.log(myFavouriteColor); // Promise {<pending>}
    // Con "await" JavaScript esperará el tiempo que sea necesario hasta
    // obtener una respuesta, tanto para bien como para mal.
    const color = await myFavouriteColor;
    // Dado que en la línea anterior tenemos un "await", este "console.log"
    // no se ejecutará hasta que el "await" anterior tenga la respuesta de la promesa.
    console.log(color); // "black"
};

// Llamamos a la función asíncrona. De lo contrario, no se ejecutará.
getColor();
```

&nbsp;

## Try...catch

La cantidad de errores que pueden surgir a la hora de trabajar con código asíncrono es muy extensa. En ocasiones nos interesará "atrapar" esos errores para poder moldearlos a nuestro gusto. Para ello haremos uso del bloque `try...catch`, muy común cuando trabajamos con funciones asíncronas.

En primer lugar se ejecuta el bloque de `try`. Si no se produce ningún error, el bloque `catch` es ignorado. Solo en caso de que se produzca un error en el primer bloque se ejecutaría el `catch`:

```javascript
try {
    // Código
} catch (error) {
    // Manejo del error.
}
```

&nbsp;

Veamos ahora un ejemplo llevado a la práctica:

```javascript
// Esta función nos devuelve un mes en función del nº que pasemos como parámetro 
// (1 = Ene, 12 = Dic).
function getMonthName(monthNumber) {
    // El primer índice del array es 0, así que adaptamos el mes instroducido por 
    // el usuario.
    const mon = monthNumber - 1;

    const months = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'];

    if (months[mon]) {
        return months[mon];
    } else {
        // La sentencia "throw" permite lanzar una excepción. Debemos especificar 
        // el valor de la excepción.
        throw 'InvalidMonthNumber';
    }
}

try {
    // En este caso saltará el "catch" dado que no existe el mes 13. Puedes probar 
    // a insertar un mes entre el 1 y el 12 para que veas que no salta al "catch" al 
    // no haber errores en el "try".
    getMonthName(13);
} catch (error) {
    console.error(error);
}
```

&nbsp;

## Finally

Existe un tercer bloque que podemos invocar al finalizar el `catch`. Este bloque es llamado `finally`, y es ejecutado SIEMPRE sin importar si el `try` ha fallado:

```javascript
try {
    // Código
} catch (error) {
    // Manejo del error.
} finally {
    // Pase lo que pase ejecuta este código.
}
```

Este último bloque no es tan habitual, pero en ocasiones requerimos su uso.

&nbsp;

Ejemplo de función asíncrona con bloque `try...catch...finally`:

```javascript
async function getCharacters() {
    try {
        const response = await fetch('https://rickandmortyapi.com/api/character');
        const data = await response.json();
        console.log(data);
    } catch(error) {
        console.log(error);
    } finally {
        console.log('La función asíncrona ha finalizado.');
    }
}

// No os olvidéis de llamar a la función asíncrona para que se ejecute.
getCharacters();
```

